<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

/**
 * @var $block Magento\AdobeStockImageAdminUi\Block\Adminhtml\Panel
 */
?>

<div id="adobe-stock-images-search-modal" style="display: none;">
    <div class="adobe-stock-images-search-modal-content">
        <?= $block->getChildHtml(); ?>
    </div>
</div>

<script type="text/x-magento-init">
    {
        "#adobe-stock-images-search-modal": {
            "Magento_Ui/js/core/app": {
                "components": {
                    "stock_panel": {
                        "component": "Magento_AdobeStockImageAdminUi/js/panel",
                        "containerId": "#adobe-stock-images-search-modal",
                        "masonryComponentPath": "adobe_stock_images_listing.adobe_stock_images_listing.adobe_stock_images_columns"
                    }
                }
	     },
            "Magento_AdobeStockImageAdminUi/js/validation/validateImageName": {}
        }
    }
</script>
