<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */
?>

<div id="adobe-stock-images-search-modal"
     data-mage-init='{"Magento_Ui/js/modal/modal":{"type":"slide","title":"<?= $block->escapeJs(__('Adobe Stock')) ?>",
         "buttons":[]}}' class="no-display">
    <div class="adobe-stock-images-search-modal-content">
        <?php echo $block->getChildHtml(); ?>
    </div>
</div>

<script>
    require(['jquery', 'mage/apply/main'], function ($, main) {
        main.apply();
        $('#adobe-stock-images-search-modal').applyBindings();
    })
</script>
