<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */
?>

<div class="media-directory-container">
    <div id="media-gallery-directory-tree"></div>
</div>

<script type="text/x-magento-init">
    {
        ".media-directory-container": {
            "Magento_MediaGalleryUi/js/directory/directoryTree": {
                "directoryListUrl": "<?= $block->getUrl("media_gallery/directories/getlist"); ?>"
            }
        }
    }
</script>
<!-- @todo remove when "UI components" will support such initialization -->
<script>
    require('mage/apply/main').apply();
</script>
