<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */
// @codingStandardsIgnoreFile

/** @var $block \Magento\AdobeStockImageAdminUi\Model\Block\Adminhtml\System\Config\TestConnection */
?>
<button class="scalable" type="button" id="<?= $block->getData('html_id') ?>" data-mage-init='{"testConnection":{
    "url": "<?= /* @escapeNotVerified */ $block->getData('ajax_url') ?>",
    "elementId": "<?= $block->getData('html_id') ?>",
    "successText": "<?= /* @escapeNotVerified */ __('Successful! Test again?') ?>",
    "headers": <?= $block->getData('headers') ?>,
    "fieldToCheck": "nb_results",
    "failedText": "<?= /* @escapeNotVerified */ __('Connection failed! Test again?') ?>",
    "fieldMapping": "<?= /* @escapeNotVerified */ $block->getData('field_mapping') ?>"}, "validation": {}}'>
    <span>
        <span>
            <span id="<?= $block->getData('html_id') ?>_result">
                <?= $block->escapeHtml($block->getData('button_label')) ?>
            </span>
        </span>
    </span>
</button>
