<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

/** @var $block \Magento\AdobeStockAdminUi\Block\Adminhtml\System\Config\TestConnection */
?>
<div data-bind="scope: 'adobe-stock-test-connection'" class="scalable">
    <!-- ko template: getTemplate() --><!-- /ko -->
</div>
<script type="text/x-magento-init">
    {
        "*": {
            "Magento_Ui/js/core/app": {
                "components": {
                    "adobe-stock-test-connection": {
                        "component": "Magento_AdobeStockAdminUi/js/connection",
                        "success": "<?= $block->escapeHtmlAttr($block->isConnectionSuccessful()) ?>",
                        "url": "<?= $block->escapeJs($block->escapeUrl($block->getAjaxUrl())) ?>",
                        "buttonLabel": "<?= $block->escapeHtml($block->getButtonLabel()) ?>"
                    }
                }
            }
        }
    }
</script>
