<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

/** @var $block \Magento\AdobeStockAsset\Model\Block\Adminhtml\System\Config\TestConnection */
?>
<script>
    require(['prototype'], function(){
//<![CDATA[
        function validateApiKey() {
            var validationMessage = $('validation_api_connection_result');
            new Ajax.Request('<?= $block->escapeJs($block->escapeUrl($block->getAjaxUrl())) ?>', {
                onSuccess: function(response) {
                    var result = '<?= $block->escapeJs($block->escapeHtml(__('Test connection to the Adobe Stock integration failed.'))) ?>';
                    try {
                        if (response.responseText.isJSON()) {
                            response = response.responseText.evalJSON();
                            result = response.message;
                        }
                        if (response.success == 1) {
                            validationMessage.removeClassName('hidden').addClassName('message message-success success')
                        } else {
                            validationMessage.removeClassName('hidden').addClassName('message message-error error')
                        }
                    } catch (e) {
                        validationMessage.removeClassName('hidden').addClassName('message message-error error')
                    }
                    validationMessage.update(result);
                }
            });
        }

        window.validateApiKey = validateApiKey;
//]]>
    });
</script>
<div id="validation_api_connection_result" class="message-validation hidden"></div>
<button onclick="javascript:validateApiKey(); return false;" class="scalable" type="button" id="<?= $block->escapeHtmlAttr($block->getHtmlId()) ?>">
    <span id="<?= $block->escapeHtmlAttr($block->getData('html_id')) ?>_result">
        <?= $block->escapeHtml($block->getData('button_label')) ?>
    </span>
</button>
