<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

/** @var $block \Magento\AdobeStockAsset\Model\Block\Adminhtml\System\Config\TestConnection */
?>
<div id="<?= $block->escapeHtmlAttr($block->getApiKeyValidationResultContainerId()) ?>" class="scalable"></div>
<button class="scalable" type="button" id="<?= $block->escapeHtmlAttr($block->getHtmlId()) ?>">
    <span id="<?= $block->escapeHtmlAttr($block->getHtmlId()) ?>_result">
        <?= $block->escapeHtml($block->getData('button_label')) ?>
    </span>
</button>
<script type="text/x-magento-init">
    {
        "#validation_api_connection_result": {
            "Magento_AdobeStockAsset/js/validate-api-key": {
                "requestValidationUrl": "<?= $block->escapeJs($block->escapeUrl($block->getAjaxUrl())) ?>",
                "testButtonId": "<?= $block->escapeHtmlAttr($block->getHtmlId()) ?>",
                "apiKeyInput": "system_adobe_stock_integration_api_key",
                "validationResultContainerId": "<?= $block->escapeHtmlAttr($block->getApiKeyValidationResultContainerId()) ?>",
                "defaultMessage": "<?= $block->escapeJs($block->escapeHtml(__('Test connection to the Adobe Stock integration failed.'))) ?>"

            }
        }
    }
</script>
